//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kurs_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Fuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fuel()
        {
            this.Emkost = new HashSet<Emkost>();
            this.Operaciya = new HashSet<Operaciya>();
        }
    
        public int FuelID { get; set; }
        [Display(Name = "Тип гсм")]
        public string FuelType { get; set; }
        [Display(Name = "Октановое число")]
        public int Oktan { get; set; }
        [Display(Name = "Цена за л")]
        public decimal Cena { get; set; }
        [Display(Name = "Дата")]
        public System.DateTime Data { get; set; }
        [Display(Name = "Описание")]
        public string About { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emkost> Emkost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operaciya> Operaciya { get; set; }
    }
}
