//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllOperacions
    {
        public System.DateTime Expr1 { get; set; }
        public double Expr2 { get; set; }
        public string Expr9 { get; set; }
        public Nullable<System.DateTime> Expr10 { get; set; }
        public Nullable<System.DateTime> Expr11 { get; set; }
        public int Expr3 { get; set; }
        public int Expr4 { get; set; }
        public int Expr5 { get; set; }
        public int Expr6 { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Otchestvo { get; set; }
        public int OperaciyaID { get; set; }
        public int EmkostID { get; set; }
        public int Nomer { get; set; }
        public double Obyem { get; set; }
        public int Expr7 { get; set; }
        public int FuelID { get; set; }
        public string FuelType { get; set; }
        public int Oktan { get; set; }
        public decimal Cena { get; set; }
        public System.DateTime Data { get; set; }
    }
}
