//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciya
    {
        public int OperaciiID { get; set; }
        public Nullable<double> Litr { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> EmkostiID { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<int> SotrudnikID { get; set; }
    
        public virtual Emkost Emkost { get; set; }
        public virtual Fuel Fuel { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
